### ISSUE TITLE
Which Tool set Use

### ISSUE THREAD

**Issue by FranklinOP-IND** [EVERDOXSUS/VanguardSussy#1]
![image](https://user-images.githubusercontent.com/64591314/157592725-10b59380-db02-4919-8082-9eb89ae61f83.png)
Error Found

**Comment by Xyrem** [comment]
Are you sure you are using battlepass simulator v28294 and UD everdox bypass? You need this. Also sorry but #1586

**Comment by Xyrem** [comment]
Oh and forgot you need grass offset

**Comment by xBreaders** [comment]
Process + 0x658 for a fix
